### ISSUE TITLE
Error thrown when evaluating dom-3 constraint on a resource with contained resources

### ISSUE THREAD

**Issue by bholyshevskyi** [HL7/fhirpath.js#126]
Steps to reproduce:
1. Open https://hl7.github.io/fhirpath.js/.
2. Paste `dom-3` constraint expression from https://www.hl7.org/fhir/domainresource.html#invs - `contained.where(((id.exists() and ('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url)))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(uri) = '#').exists()).not()).trace('unmatched', id).empty()`
3. Use JSON below as an input:
```
{
  "resourceType": "GuidanceResponse",
  "contained": [
    {
      "resourceType": "Parameters",
      "id": "outputParameters1",
      "parameter": [
        {
          "name": "score",
          "valueDecimal": 7
        }
      ]
    }
  ],
  "moduleUri": "http://someguidelineprovider.org/radiology-appropriateness-guidelines.html",
  "status": "success",
  "outputParameters": {
        "reference": "#outputParameters1"
  }
}
```
ER:  The expression is evaluated to `true`.
AR: `Error: Attempting to access an undefined environment variable: resource` erros is thrown.

Tested on version 3.0.0.

**Comment by plynchnlm** [comment]
The demo at https://hl7.github.io/fhirpath.js/ does not provide a way to define environment variables, and the expression above refers to "%resource" which is not defined.  The JSON input provides the %context variable, which is not always the same thing as %resource.  If you download fhirpath.js, the API provides a way to specify %resource or any other variable.

As a work around for this limitation of the demo, you could replace %resource with %context, since in your case they are the same thing.  Then you will run into the error "Error: Not implemented: as", because "as" is not implemented in the currently published version.  However, that implementation has been done, and is just pending a merge and a publish-- so it should work soon.

**Comment by plynchnlm** [comment]
The FHIRPath engine needs to be told what %resource is.  What you are providing on that demo page is %context, which per your link above, if often the same, but sometimes not.
