### ISSUE TITLE
Unable to load in browser

### ISSUE THREAD

**Issue by bpetty-formfast** [HL7/fhirpath.js#23]
After downloading and extracting the library from fhirpath.zip, and trying to load it, I get an exception detailed below.  Setting the type to "module" appears to get further, but I get a "fhirpath is not defined" error from within the .js.  I cannot find any example of loading this in the browser.  Could you provide one?

```html
<html>
<head>
	<!-- Throws: 59627784-3BE5-417A-B9EB-8131A7286089 -->
	<script src="fhirpath.min.js"></script>
	<script>
		if (typeof fhirpath === "undefined") console.log('FHIRPath Not Loaded');
	</script>
</head>
</html>
```

**Comment by bpetty-formfast** [comment]
Basically before, the library was throwing an exception that, when caught, was some GUID.  I tried building from source to run the protractor tests but noticed that the scripts used a "CP" command to copy... which does not work on Windows.  After manually running WebPack in the browser-build folder I was able to generate a fhirpath.min.js script.  This scripts is about 3 times as big as the one available for download on the site (618KB vs 219KB).  It seems to load correctly now.  It looks like there may be a few issues: 

1. It wont really build on windows, without work-arounds
2. What ever is being uploaded on the site appears to be broken
3. 618KB seems a little big for a parser, to be honest.

**Comment by plynchnlm** [comment]
This obscure exception comes from the ANTLR parser code and is due to the fact that fhirpath.min.js is encoded in UTF-8.  The browser must be told that fhirpath.min.js is UTF-8, which can either be done on the script tag (thought charset is deprecated there), or by including "<meta charset="utf-8">" in the HEAD portion of the webpage, or by setting "Content-Type: application/javascript; charset=UTF-8" as an HTTP response header (server side).

I had not really worried about Linux commands being present in the build, because I was not expecting people to run the build unless they were doing development, so far all of those people have been using Linux.  But, I think you are the second person to try it.  It looks like there are webpack plugins that could replace those commands.

Regarding the size, I can't imagine why it would build larger on Windows than on Linux.  I am about to merge a branch that will make it that large, but most of that increase is a data file (for unit conversions) that gzips down nicely, so I am not too worried.  I would guess most servers will gzip resources before sending.  However, that branch is not merged yet, so it shouldn't be reason for the size you are seeing.

Anyway, try the charset setting.  I will be updating the example file in the test (browser-build/test/protractor/index.html) to include the needed meta tag.  (Curiously, the server used by the test automatically included the right HTTP response header, which is why the tests passed.)  I will also add a note to the documentation about the UTF-8 encoding.

**Comment by plynchnlm** [comment]
Closing because I think the Windows build issue is fixed, and I have not heard back on the the other problem.
