### ISSUE TITLE
Support for 3.2 Paths and Polymorphic Items?

### ISSUE THREAD

**Issue by xcskier56** [HL7/fhirpath.js#31]
Hi there,

I'm currently evaluating this library for use in an ionic/angular Smart on FHIR application. One of the best use cases I can see for this is to help deal with polymorphic items per section 3.2 of the fhirPath spec. Specifically, I'm hoping to deal with the `value[x]` within questionnaires and questionnaireResponses. 

However, as far as I can tell, this is not currently supported. If I'm wrong, could we please update the implementation status, and potentially add an example? 

If this is not currently supported, is this on the roadmap? I'd be happy to help work on implementing it with some guidance.

Thanks

**Comment by plynchnlm** [comment]
As it happens, support for polymorphic types was the next thing I was planning to implement for fhirpath.js, though it would probably be done in my spare time (so it might be a few weeks).  I would be happy to provide guidance on how to implement it if you are interested in doing the work.  It is not trivial, because I would suppose that which fields are polymorphic will vary on the version of FHIR, and a list of the polymorphic fields (and resource paths) would need to be pre-generated.  The internal structure of the parsed JSON would need to modified to store the type of the polymorphic field.  We already have some modifications like that for date/time data (subclasses of "FP_Type").

**Comment by xcskier56** [comment]
Great timing! If you're planning on implementing this next, I'll leave it to you. It might be more work to get me up to speed than its worth. If you'd be so kind as to push your work to a branch, I'd love to follow along to begin to understand how the project works!

**Comment by plynchnlm** [comment]
Are you using fhirpath.js with R4 or STU3?  The set of polymorphic fields is potentially different.  The FHIRPath schema is also slightly different (though I've been ignoring that).  I think I am going to have reorganize the code to have separate "requires" for R4 FHIRPath and STU3 FHIRPath.

**Comment by xcskier56** [comment]
Both 🙄. Its complicated but we're going to move to just supporting R4 in the near future.

**Comment by plynchnlm** [comment]
See release 1.0.0, which has support for "choice types".  Operators "is" and "as" won't work yet, but you can now write ".value" instead of ".valueQuantity".
