### ISSUE TITLE
ResourceNode constructor when data argument is undefined

### ISSUE THREAD

**Issue by mgunnerud** [HL7/fhirpath.js#44]
If 'data' argument of ResourceNode constructor is undefined or null, execution will crash when trying to evaluate data.resourceType:

https://github.com/HL7/fhirpath.js/blob/d8567a2a15d9b9f0c6b1dabe872c89fb9bb8ca8f/src/types.js#L978

This can occur when looping through object properties in engine.children, if one of these properties is undefined:

https://github.com/HL7/fhirpath.js/blob/d8567a2a15d9b9f0c6b1dabe872c89fb9bb8ca8f/src/navigation.js#L25

**Comment by plynchnlm** [comment]
Thanks for this report.  I can see that if one puts in null for a resource property, one gets an error, but I am not sure what to do about that, because I don't think null is a valid value for a resource property.  Do you have an example expression and resource-like structure that demonstrates the problem?

**Comment by plynchnlm** [comment]
Closing due to lack of response.
