### ISSUE TITLE
Proper browser support

### ISSUE THREAD

**Issue by SvetlozarValchev** [HL7/fhirpath.js#49]
Can't you make it so you can `npm install` and load the modules for a browser app? The method of downloading zips and including them in your project is extremely outdated.

**Comment by SvetlozarValchev** [comment]
I'm using Nuxt (Vue.js and Webpack). After some fiddling around I found the most optimal way through npm: 

```
import {evaluate} from 'fhirpath/src/fhirpath';
import fhirpath_stu_3 from 'fhirpath/fhir-context/stu3/index'
```

Though for IE11 support I had to put these folders through the transpiler:  

nuxt.config.js
```
  build: {
    transpile: ['fhirpath/src', '@lhncbc/ucum-lhc'],
  }
```

**Comment by plynchnlm** [comment]
That raises an interesting point.  @lhncbc/ucum-lhc, which is a dependency, also requires transpiling.  So, just providing transpiled code for fhirpath.js would not be sufficient.  We could include the browser-build bundle, so that you could load that with "require('fhirpath/browser-build/fhirpath.min.js')".  The disadvantage of doing that, generally speaking, is that if you depend on packages A and B, and A also depends on B, then if you load a pre-bundled version of A that includes B, your app will be loading two copies of B (one inside the A bundle, and one picked up through your app's dependencies').  The two versions might conflict with each other, which is a situation a package manager is designed to resolve.  Maybe you don't use package @lhncbc/ucum-lhc directly, but what about its dependencies (like maybe cvs-parse) which will also be in the browser-ready fhirpath.min.js bundle?
But I suppose we could go ahead and include it and warn users about the potential issues.

**Comment by SvetlozarValchev** [comment]
Including the browser-ready files in <head> actually causes problems in IE11:

![image](https://user-images.githubusercontent.com/446056/84416173-8645bb00-ac1c-11ea-99b7-068f281e77a4.png)

So the import approach I mentioned above is more reliable in terms of compatibility with older browsers.

**Comment by plynchnlm** [comment]
The browser-ready files are supposed to support IE 11, and we have a test page for the build at browser-build\test\protractor\index.html which we check in IE 11 each release.  The test page includes the script tags in the body, though, not head.  Usually, in most cases best practice is to include script tags at the end of the body section, though perhaps your needs are different.  Anyway, if you have a test case you can share that demonstrates that error, please report it as a separate issue.

**Comment by plynchnlm** [comment]
Closing due to lack of response.  Feel free to reopen if it is still an issue and you can provide a test case.
